# Generated by Django 2.2.7 on 2019-11-26 21:20

from django.db import migrations


def create_data(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    Patient(first_name="Micahel", last_name="Wells", mrn = 111111, sex="M", race="NA", diagnosis = "GBM", description= "Customer 001 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_data),
    ]
